/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../app/app.module';
import * as import2 from './app.component.ngfactory';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _AppModule_0:import1.AppModule;
  constructor(parent:import0.Injector) {
    super(parent,[import2.AppComponentNgFactory],[import2.AppComponentNgFactory]);
  }
  createInternal():import1.AppModule {
    this._AppModule_0 = new import1.AppModule();
    return this._AppModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.AppModule)) { return this._AppModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3RoaW5rYWRpL0RvY3VtZW50cy9yZXBvcy9naXRodWIvdXNlcnMvdGhpbmthZGkvbWVhbi11bml2ZXJzYWwtc3RhcnRlci9zcmMvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvdGhpbmthZGkvRG9jdW1lbnRzL3JlcG9zL2dpdGh1Yi91c2Vycy90aGlua2FkaS9tZWFuLXVuaXZlcnNhbC1zdGFydGVyL3NyYy9hcHAvYXBwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
